adhearsion_hammer {
  #Context used to treat calls generated by the Hammer Class
  
  #First we collect the variables from the Asterisk channel with instructions on what to do with this call
  send_dtmf = get_variable "send_dtmf"
  call_length = get_variable "call_length"
  before_delay = get_variable "before_delay"
  after_delay = get_variable "after_delay"
  message = get_variable "message"
  
  #Now, lets treat the call
  sleep before_delay.to_i
  if send_dtmf != nil
    dtmf send_dtmf
    sleep after_delay.to_i
  end
  if message != nil
    play message
  end
  sleep call_length.to_i
}